version: "3.8"

services:
  web:
    image: nginx:alpine
    depends_on:
      - php-app
    ports:
      - "8080:80"        
    volumes:
      - ./php-app:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf.bak 2>/dev/null; exec nginx -g 'daemon off;'"
    networks:
      - ctf-net

  php-app:
    build: ./php-app
    depends_on:
      - db
    volumes:
      - ./php-app:/var/www/html:rw
    networks:
      - ctf-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ctf
      MYSQL_USER: ctf
      MYSQL_PASSWORD: ctfpass
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./php-app:/var/www/html:rw
    networks:
      - ctf-net

  file-fixer:
    image: alpine:3.18
    container_name: noisy_ctf_file_fixer
    user: root
    depends_on:
      - db
      - php-app
    volumes:
      - ./php-app:/var/www/html:rw
      - ./file-fixer/fixperms-loop.sh:/fixperms-loop.sh:ro
    entrypoint: ["/bin/sh", "/fixperms-loop.sh"]
    environment:
      - TARGET=/var/www/html
      - INTERVAL=1
      - VERBOSE=1
    networks:
      - ctf-net

networks:
  ctf-net:
    driver: bridge

